/* Premium / Revenue Analysis -
What this section answers
How much premium revenue does the company generate?
Which policy types generate the most premium?
Which customer segments generate the most revenue?
How does risk level relate to premium?
Which acquisition channels generate revenue?
Which agents generate the most premium?
How is premium changing over time? */


-- 1. Total premium revenue
SELECT 
    SUM(Premium_Amount) AS Total_Premium_Revenue
FROM Policies;



-- 2. Premium by policy type
SELECT
    Policy_Type,
    COUNT(*) AS Total_Policies,
    SUM(Premium_Amount) AS Total_Premium,
    AVG(Premium_Amount) AS Average_Premium
FROM Policies
GROUP BY Policy_Type
ORDER BY Total_Premium DESC;




-- 3. Premium by customer segment
SELECT
    c.Customer_Segment,
    COUNT(p.Policy_ID) AS Total_Policies,
    SUM(p.Premium_Amount) AS Total_Premium,
    AVG(p.Premium_Amount) AS Average_Premium
FROM Policies p
JOIN Customers c
    ON p.Customer_ID = c.Customer_ID
GROUP BY c.Customer_Segment
ORDER BY Total_Premium DESC;




-- 4. Premium by risk category
SELECT
    Risk_Category,
    COUNT(*) AS Total_Policies,
    SUM(Premium_Amount) AS Total_Premium,
    AVG(Premium_Amount) AS Average_Premium
FROM Policies
GROUP BY Risk_Category
ORDER BY Total_Premium DESC;




-- 5. Premium by acquisition channel
SELECT
    Acquisition_Channel,
    COUNT(*) AS Total_Policies,
    SUM(Premium_Amount) AS Total_Premium
FROM Policies
GROUP BY Acquisition_Channel
ORDER BY Total_Premium DESC;




-- 6. Premium by payment frequency
SELECT
    Payment_Frequency,
    COUNT(*) AS Total_Policies,
    SUM(Premium_Amount) AS Total_Premium,
    AVG(Premium_Amount) AS Average_Premium
FROM Policies
GROUP BY Payment_Frequency
ORDER BY Total_Premium DESC;




-- 7. Premium by year
SELECT
    YEAR(Policy_Start_Date) AS Policy_Year,
    COUNT(*) AS Total_Policies,
    SUM(Premium_Amount) AS Total_Premium
FROM Policies
GROUP BY YEAR(Policy_Start_Date)
ORDER BY Policy_Year;




-- 8. Top 10 customers by premium generated
SELECT
    c.Customer_ID,
    c.Customer_Name,
    COUNT(p.Policy_ID) AS Total_Policies,
    SUM(p.Premium_Amount) AS Total_Premium
FROM Customers c
JOIN Policies p
    ON c.Customer_ID = p.Customer_ID
GROUP BY c.Customer_ID, c.Customer_Name
ORDER BY Total_Premium DESC
LIMIT 10;




-- 9. Premium contribution by policy type (%)
SELECT
    Policy_Type,
    SUM(Premium_Amount) AS Total_Premium,
    ROUND(
        SUM(Premium_Amount) * 100.0 /
        (SELECT SUM(Premium_Amount) FROM Policies),
        2
    ) AS Premium_Contribution_Pct
FROM Policies
GROUP BY Policy_Type
ORDER BY Total_Premium DESC;




-- 10. Premium generated by agents
SELECT
    a.Agent_ID,
    a.Agent_Name,
    COUNT(p.Policy_ID) AS Total_Policies,
    SUM(p.Premium_Amount) AS Calculated_Premium
FROM Agents a
JOIN Policies p
    ON a.Agent_ID = p.Agent_ID
GROUP BY a.Agent_ID, a.Agent_Name
ORDER BY Calculated_Premium DESC;